Restoring bigdecimal to fix deploy
When attempting to deploy changes via capistrano, I see the following
error:

```console
rake stderr: rake aborted!
LoadError: cannot load such file -- bigdecimal
```

In restoring bigdecimal (removed in ddb96b18b949441b1d947793f18ef5669d52da1e)
I hope to get past the blockers for Capistrano based deploys